name: Publish package to npmjs

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 🛒 Checkout branch
        uses: actions/checkout@v3

      - name: ✨ Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.21

      - uses: actions/cache@v3
        name: Setup deps cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: ➕ Install dependencies
        run: bun install --frozen-lockfile

      - name: 📦 Build
        run: bun run build

      - name: 🔖 Release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
